repos:
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.8
    hooks:
      - id: nbqa-mypy
        args: ["--nbqa-ignore-cells=%%R", "--strict", "--show-error-codes"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        args: ["--strict", "--show-error-codes"]
