repos:
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.6.0
    hooks:
      - id: nbqa-mypy
        args: ["--strict", "--show-error-codes", "--pretty", "--show-error-context"]
        additional_dependencies:
        - mypy==0.812
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: ["--strict", "--show-error-codes", "--pretty", "--show-error-context"]
